"""
build-kanji.py - Regenerates js/data/kanji.js, Benkyou's kanji datasheet.

Download these three files into one folder first:

  kanjidic2.xml.gz  https://www.edrdg.org/kanjidic/kanjidic2.xml.gz
  kanji-data.json   https://raw.githubusercontent.com/davidluzgouveia/kanji-data/master/kanji.json
  joyo-wiki.html    https://en.wikipedia.org/wiki/List_of_j%C5%8Dy%C5%8D_kanji  (save the page HTML)

Then, from the repo root:

  py tools/build-kanji.py path/to/that/folder

The script asserts the Jōyō counts (2,136 total, and the 2020 per-grade split) and
exactly 2,500 frequency-ranked kanji. If Wikipedia's table layout changes, the
Jōyō assertion is the one that will fail.
"""
import collections, gzip, html, json, re, sys
import xml.etree.ElementTree as ET
from pathlib import Path

sys.stdout.reconfigure(encoding="utf-8")

SRC = Path(sys.argv[1] if len(sys.argv) > 1 else ".")
OUT = Path(__file__).resolve().parent.parent / "js" / "data" / "kanji.js"

# --- KANJIDIC2: strokes, frequency, readings, meanings ---
raw = gzip.open(SRC / "kanjidic2.xml.gz", "rb").read()
version = re.search(rb"<database_version>(.*?)</database_version>", raw).group(1).decode()
kd = {}
for ch in ET.fromstring(raw).iter("character"):
    misc = ch.find("misc")
    kd[ch.findtext("literal")] = {
        "strokes": int(misc.find("stroke_count").text),
        "freq": int(misc.findtext("freq")) if misc.findtext("freq") else None,
        "on": [r.text for r in ch.iter("reading") if r.get("r_type") == "ja_on"],
        "kun": [r.text for r in ch.iter("reading") if r.get("r_type") == "ja_kun"],
        "meanings": [m.text for m in ch.iter("meaning") if m.get("m_lang") is None],
    }

# --- Wikipedia Jōyō table: order and grade ---
page = (SRC / "joyo-wiki.html").read_text(encoding="utf-8")
joyo = []  # (table index, character, grade)
for row in page.split("</tr>"):
    cells = [html.unescape(re.sub(r"<[^>]+>", "", c)).strip()
             for c in re.findall(r"<td[^>]*>(.*?)</td>", row, re.S)]
    if len(cells) >= 6 and cells[0].isdigit():
        joyo.append((int(cells[0]), cells[1][0], cells[5]))

GRADE_ORDER = ["1", "2", "3", "4", "5", "6", "S"]
assert len(joyo) == 2136, f"expected 2136 Jōyō rows, got {len(joyo)}"
counts = collections.Counter(g for _, _, g in joyo)
assert [counts[g] for g in GRADE_ORDER] == [80, 160, 200, 202, 193, 191, 1110], counts
joyo.sort(key=lambda t: (GRADE_ORDER.index(t[2]), t[0]))
grade_of = {c: g for _, c, g in joyo}

# --- JLPT (Jonathan Waller's lists, via kanji-data) ---
kanji_data = json.loads((SRC / "kanji-data.json").read_text(encoding="utf-8"))
jlpt = {k: v["jlpt_new"] for k, v in kanji_data.items() if v.get("jlpt_new")}

# --- Which kanji, in what order ---
order = [c for _, c, _ in joyo]
seen = set(order)
freq_extra = sorted((c for c, e in kd.items() if e["freq"] and e["freq"] <= 2500 and c not in seen),
                    key=lambda c: kd[c]["freq"])
order += freq_extra
seen |= set(freq_extra)
jlpt_extra = sorted((c for c in jlpt if c not in seen), key=lambda c: (-jlpt[c], c))
order += jlpt_extra

assert all(c in kd for c in order)
assert sum(1 for c in order if kd[c]["freq"] and kd[c]["freq"] <= 2500) == 2500


def entry(c):
    e = kd[c]
    g = grade_of.get(c)
    return {
        "strokes": e["strokes"],
        "grade": int(g) if g and g.isdigit() else g,
        "freq": e["freq"] if e["freq"] and e["freq"] <= 2500 else None,
        "jlpt": jlpt.get(c),
        "on": e["on"],
        "kun": e["kun"],
        "meanings": e["meanings"],
    }


lines = [
    "/**",
    " * kanji.js - Benkyou's kanji datasheet. GENERATED by tools/build-kanji.py, do not edit by hand.",
    " *",
    f" * {len(order)} kanji: the 2,136 Jōyō (in school-grade order, then Wikipedia's order",
    " * within a grade), then the rest of KANJIDIC2's 2,500 most frequent (by rank), then",
    " * any remaining kanji on a JLPT list (by level).",
    " *",
    " *   strokes   KANJIDIC2 stroke count",
    " *   grade     1-6 = kyōiku grade, 'S' = secondary-school Jōyō, null = not Jōyō",
    " *   freq      newspaper frequency rank 1-2500, null = outside the 2,500",
    " *   jlpt      5-1 for N5-N1, null = on no list (unofficial lists; there is no official one)",
    " *   on / kun / meanings  exactly as KANJIDIC2 gives them",
    " *",
    " * Sources:",
    f" *   KANJIDIC2 (database version {version}), © Electronic Dictionary Research and",
    " *     Development Group, CC BY-SA 4.0 - https://www.edrdg.org/edrdg/licence.html",
    " *   Jōyō grades: Wikipedia, \"List of jōyō kanji\" (2020 kyōiku revision), CC BY-SA 4.0",
    " *   JLPT levels: Jonathan Waller's JLPT lists (tanos.co.uk), CC BY, as merged in",
    " *     github.com/davidluzgouveia/kanji-data (MIT)",
    " */",
    f"export const KANJIDIC_VERSION = '{version}';",
    "",
    "export const KANJI = {",
]
for c in order:
    lines.append(f"  {json.dumps(c, ensure_ascii=False)}: "
                 f"{json.dumps(entry(c), ensure_ascii=False, separators=(', ', ': '))},")
lines.append("};")

text = "\n".join(lines) + "\n"
OUT.parent.mkdir(parents=True, exist_ok=True)
OUT.write_text(text, encoding="utf-8", newline="\n")

print(f"KANJIDIC2 {version}: wrote {len(order)} kanji to {OUT}")
print(f"  {len(joyo)} Jōyō, {len(freq_extra)} more from the top 2,500, {len(jlpt_extra)} more from JLPT lists")
print(f"  {len(text.encode()):,} bytes")
